# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  run_client_test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: cd ./client && npm install --save
      - run: npm --prefix ./client run test:unit
workflows:
  version: 2
  build_test:
    jobs:
      - run_client_test
    