insert into films(title, description, directors, published, created_at, updated_at)
values ('The Shawshank Redemption',
        'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
        'Frank Darabont', false, now(), now()),
       ('The Godfather', 'An organized crime dynasty''s aging patriarch transfers control of his clandestine empire to his reluctant son.
', 'Francis Ford Coppola', false, now(), now()),
       ('The Godfather: Part II',
        'The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.',
        'Francis Ford Coppola', false, now(), now()),
       ('The Dark Knight',
        'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
        'Christopher Nolan', false, now(), now()),
       ('12 Angry Men',
        'A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.',
        'Sidney Lumet', true, now(), now()),
       ('Список Шиндлера',
        'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.',
        'Steven Spielberg', false, now(), now()),
       ('The Lord of the Rings: The Return of the King',
        'Gandalf and Aragorn lead the World of Men against Sauron''s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.',
        'Peter Jackson', true, now(), now()),
       ('Pulp Fiction',
        'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
        'Quentin Tarantino', false, now(), now()),
       ('Il buono, il brutto, il cattivo',
        'A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.',
        'Sergio Leone', false, now(), now()),
       ('The Lord of the Rings: The Fellowship of the Ring',
        'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.',
        'Peter Jackson', true, now(), now());
